name: Update README with Recent Activity

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "activity"
          feed_list: "https://github.com/SKgain.atom"
          max_post_count: 5
          template: "$newline- $date: $title"
          date_format: "dd mmm yyyy"
